[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/install.html"
  to = "/.netlify/functions/install"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200
  force = false
