[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  included_files = ["index.html", "install.html", "admin.html"]

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"
    Pragma = "no-cache"

[[redirects]]
  from = "/install.html"
  to = "/.netlify/functions/install"
  status = 200
  force = true

[[redirects]]
  from = "/index.html"
  to = "/.netlify/functions/index"
  status = 200
  force = true

[[redirects]]
  from = "/"
  to = "/.netlify/functions/index"
  status = 200
  force = true

[[redirects]]
  from = "/admin.html"
  to = "/.netlify/functions/admin"
  status = 200
  force = true
